### ISSUE TITLE
Json response in an iframe

### ISSUE THREAD

**Issue by worldspawn** [boxuk/tinymce-imageupload#3]
Hey, in chrome, this fails

`returnReponse = $.parseJSON(response.html());`

That line is from the iframe post plugin. The json response is getting a <pre> tag wrapped around it. This definitely isn't coming over the wire, rather chrome seems to inject it. Have u tried this in chrome?

Chrome also warns:

Resource interpreted as Document but transferred with MIME type application/json:

**Comment by worldspawn** [comment]
Setting the content type to text/plain resolves the warning, but not the error.

**Comment by worldspawn** [comment]
So it works in IE (10).

This issue was easily solved by replacing .html() with .text(). I'd call this a bug in that iframe script as this run inside 

```
if (options.json)
```

so why on earth would anyone want html in their json?

```
returnReponse = $.parseJSON(response.text());
```

Ewen Elder's webpage is disgusting..! Can't figure out how to get a message to him. Facebook comments on his page are broken.

**Comment by rogerthomas84** [comment]
@worldspawn ironically, I found the exact same thing the other day. I was contemplating adding the fix to this repo. If you setup a repo with the fix in, and change the readme, then I'll point people over to your repo for the WORKING version of the iframe uploader.

**Comment by worldspawn** [comment]
Do you mean include a fixed version of the iframe script with the repo?

**Comment by rogerthomas84** [comment]
@worldspawn If you're able to, can you do this?
- Setup a repo on your GitHub with the iframe uploader script
- Submit a PR to this repo with a change to the readme file that represents the location of the iframe uploader that works (on your GitHub).

Alternatively, if you add it to a gist and send me the link then I don't mind doing it.

**Comment by rogerthomas84** [comment]
Resolved by @worldspawn so closing the issue now.
